version: '3.7'

services:
  nodejs:
    image: amarofashion-service-dev
    build:
      context: .
      target: development
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: .env
    environment:
      - MONGO_DB_URL='mongodb://mongodb/amarofashion'
      - RABBIT_MQ_URL='amqp://guest:guest@rabbitmq:5672'
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app
    depends_on:
      - mongodb
      - rabbitmq
    links:
      - mongodb
      - rabbitmq
    command: yarn start:dev

  mongodb:
    image: mongo:4.1.8-xenial
    restart: unless-stopped
    env_file: .env
    ports:
      - '27017:27017'
    volumes:
      - dbdata:/data/mongodb

  rabbitmq:
    image: rabbitmq:3-management-alpine
    restart: unless-stopped
    env_file: .env
    ports:
      - '15672:15672'
      - '5672:5672'
      - '25676:25676'
    volumes:
      - dbdata:/data/rabbitmq

volumes:
  dbdata:
